# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdcdfca6a6aea03ea708e3f74f1ebe847ca70aa5f280533509be17a99b4d522a497f37b889e007a287f80730c759bc0e38f4d67617decc348fba5f0db3820ad9

test:
  secret_key_base: 41ed8549d9360ff75b74831b020941e9376a15753a5a11c77ddf6ff9e12d20307630a63b40a85b4fb277db4aaa76bbb0cf7e5dd7a35f9809a4196b73149a509d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
